<h2 class="mt-4">Adicionar Veículos</h2>
<form action="" method="post">
    <label for="make">Marca</label>
    <input type="text" name="make" id="make"  class="form-control">
    <br>

    <label for="model">Modelo</label>
    <input type="text" name="model" id="model"  class="form-control">
    <br>

    <label for="year">Ano</label>
    <input type="text" name="year" id="year"  class="form-control">
    <br>

    <label for="mileage">KM</label>
    <input type="text" name="mileage" id="mileage"  class="form-control">
    <br>

    <label for="plate">Placa</label>
    <input type="text" name="plate" id="plate"  class="form-control">
    <br>

    <button type="submit" class="btn btn-primary">Enviar</button>
</form>