<div class="row card-designer">
    <div class="col">
        <div class="card p-2">
            <h2 class="card-title">Lista de Veículos</h2>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead class="bg-dark text-white">
                    <tr>
                        <th>Marca</th>
                        <th>Modelo</th>
                        <th>Ano</th>
                        <th>Km</th>
                        <th>Placa</th>
                        <th>Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($vehicles as $vehicle) {
                        echo "
                    <tr>
                        <td>{$vehicle->getMake()}</td>
                        <td>{$vehicle->getModel()}</td>
                        <td>{$vehicle->getYear()}</td>
                        <td>{$vehicle->getMileage()}</td>
                        <td>{$vehicle->getPlate()}</td>
                        <td>
                            <a href='/veiculos/editar?id={$vehicle->getId()}' class='btn btn-warning btn-sm'>Editar</a>
                            <a href='/veiculos/excluir?id={$vehicle->getId()}' class='btn btn-danger btn-sm'>Excluir</a>
                        </td>
                    </tr>";
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>